package myPackage;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author Johnara
 */
public class RangeTreeGUI extends javax.swing.JFrame {

    /**
     * Creates new form RangeTreeGUI
     */
    JFrameCompleteQuery query_window;
    myPackage.FileParser file_parser = new FileParser();
    myPackage.Range_tree range_tree ;
    public DiagramGraph diagram;

    public RangeTreeGUI() {
        initComponents();
        this.setVisible(true);
    }

  public void choose_file() {


      JFileChooser fc = new JFileChooser();//to choose owl file
            FileNameExtensionFilter filter = new FileNameExtensionFilter("csv , txt", "csv","txt");//limiting files
            JButton open = new JButton();
            fc.setFileFilter(filter);
            fc.setDialogTitle("Choose your input file.");
            fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            if (fc.showOpenDialog(open) ==JFileChooser.APPROVE_OPTION){
                try {
                    String uri = fc.getSelectedFile().getPath();
                    System.out.println(uri);
                    file_parser.set_filename(uri);
                    //  int start = System.nanoTime;;

                    range_tree = new Range_tree(file_parser.items(), file_parser.dimensions() - 1,file_parser.column_names()); //dimension-1 because we handle the first dimension as dimension 0

                     // make the process last a while
                    this.jButtonQuery.setEnabled(true);
                    this.jButtonLoadData.setEnabled(false);
                    jComboBoxHorizontal.setEnabled(true);
                    jComboBoxVertical.setEnabled(true);
                    jLabelGraphDimensions.setEnabled(true);
                    jButtonGenerateGraph.setEnabled(true);
                    String[] dimensions_strings = new String[file_parser.column_names().size()];

                    for (int x = 0; x <= dimensions_strings.length-1; x++) {
                        dimensions_strings[x]= file_parser.column_names().get(x);
                    }

                    jComboBoxHorizontal.setModel(new javax.swing.DefaultComboBoxModel<>(dimensions_strings));

                    jComboBoxHorizontal.setSelectedIndex(0);
                    jLabelHorizontal.setText(dimensions_strings[0]);

                    if(dimensions_strings.length>1) {
                        jComboBoxVertical.setModel(new javax.swing.DefaultComboBoxModel<>(dimensions_strings));
                        jComboBoxVertical.setSelectedIndex(1);
                        jLabelVertical.setText(convert_to_vertical(dimensions_strings[1]));
                    }

                    generate_graph();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Something went wrong.\nPlease check the help tab on the upper left!");
                }
    }


    }

    public void refreshMe() {

        revalidate();
        repaint();
        // Need some help here:
        // I don't know what should I write, how to make a repaint of myPanel?
        System.out.println("just test, if the method refreshMe working by clicking some button");
    }

    private String convert_to_vertical(String dimensions_string) {
        String vertical_string="<html>";
        for (int i = 0; i <= dimensions_string.length()-1; i++) {
            vertical_string += dimensions_string.charAt(i) + "<br>";
        }
        vertical_string += "</html>";
        return vertical_string;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    private void initComponents() {

        jLabelVertical = new javax.swing.JLabel();
        jLabelHorizontal = new javax.swing.JLabel();
        jPanelTools = new javax.swing.JPanel();
        jButtonDelimiter = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextDelimiter = new javax.swing.JTextPane();
        jButtonLoadData = new javax.swing.JButton();
        jProgressBarTree = new javax.swing.JProgressBar();
        jLabelPercent = new javax.swing.JLabel();
        jButtonQuery = new javax.swing.JButton();
        jComboBoxVertical = new javax.swing.JComboBox<>();
        jComboBoxHorizontal = new javax.swing.JComboBox<>();
        jLabelGraphDimensions = new javax.swing.JLabel();
        jButtonGenerateGraph = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHelp = new javax.swing.JMenu();
        jMenuReset = new javax.swing.JMenu();
        jMenuTools = new javax.swing.JMenu();


        jComboBoxHorizontal.setEnabled(false);
        jComboBoxVertical.setEnabled(false);
        jLabelGraphDimensions.setEnabled(false);
        jButtonGenerateGraph.setEnabled(false);
        jButtonQuery.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelVertical.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelHorizontal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonDelimiter.setText("Set delimiter");
        jButtonDelimiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelimiterActionPerformed(evt);
            }
        });

        jTextDelimiter.setText(",");
        jScrollPane2.setViewportView(jTextDelimiter);

        jButtonLoadData.setText("Load Data");
        jButtonLoadData.setEnabled(false);
        jButtonLoadData.setMaximumSize(new java.awt.Dimension(91, 23));
        jButtonLoadData.setMinimumSize(new java.awt.Dimension(91, 23));
        jButtonLoadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadDataActionPerformed(evt);
            }
        });

        jLabelPercent.setText("0%");

        jButtonQuery.setText("Query");
        jButtonQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQueryActionPerformed(evt);
            }
        });

        jLabelGraphDimensions.setText("Select Graph Dimensions");

        jButtonGenerateGraph.setText("Generate Graph");
        jButtonGenerateGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateGraphActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelToolsLayout = new javax.swing.GroupLayout(jPanelTools);
        jPanelTools.setLayout(jPanelToolsLayout);
        jPanelToolsLayout.setHorizontalGroup(
                jPanelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelToolsLayout.createSequentialGroup()
                                .addGroup(jPanelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelToolsLayout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jButtonDelimiter))
                                        .addGroup(jPanelToolsLayout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelToolsLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jButtonLoadData, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelToolsLayout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addComponent(jLabelPercent))
                                        .addGroup(jPanelToolsLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanelToolsLayout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jButtonQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jProgressBarTree, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanelToolsLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jComboBoxVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelToolsLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jComboBoxHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelToolsLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabelGraphDimensions))
                                        .addGroup(jPanelToolsLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jButtonGenerateGraph)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelToolsLayout.setVerticalGroup(
                jPanelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelToolsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonDelimiter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonLoadData, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabelPercent)
                                .addGap(1, 1, 1)
                                .addComponent(jProgressBarTree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonQuery)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelGraphDimensions)
                                .addGap(8, 8, 8)
                                .addComponent(jComboBoxVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonGenerateGraph)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuHelp.setText("Help");
        jMenuHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHelpMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuHelp);

        jMenuReset.setText("Reset");
        jMenuReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuResetMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuReset);


        jMenuTools.setText("Tools");
        jMenuTools.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuToolsMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuTools);
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelVertical, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jPanelTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabelVertical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jPanelTools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(6, 6, 6))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        pack();
    }//

    private void jMenuToolsMouseClicked(MouseEvent evt) {
        jPanelTools.setVisible(!jPanelTools.isVisible());
    }

    private void jButtonGenerateGraphActionPerformed(ActionEvent evt) {
       generate_graph();
        jPanelTools.setVisible(false);
    }

    private void generate_graph() {
        if(diagram!=null) remove(diagram);
        else {setLayout(new BorderLayout());}
        if( range_tree!=null) {
            diagram = new DiagramGraph(range_tree.items(),jComboBoxHorizontal.getSelectedIndex(),jComboBoxVertical.getSelectedIndex());
            add(diagram, BorderLayout.CENTER);
        }

        jLabelVertical.setText(convert_to_vertical(jComboBoxVertical.getItemAt(jComboBoxVertical.getSelectedIndex())));
        jLabelHorizontal.setText(jComboBoxHorizontal.getItemAt(jComboBoxHorizontal.getSelectedIndex()));
        refreshMe();
    }

    private void jButtonLoadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadDataActionPerformed
  choose_file();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoadDataActionPerformed

    private void jButtonQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQueryActionPerformed
         query_window = new JFrameCompleteQuery(range_tree,file_parser.column_names(),this);
        query_window.setVisible(true);
        jButtonQuery.setEnabled(false);
        query_window.addWindowListener( new WindowAdapter()
        {
            public void windowClosing(WindowEvent e)
            {
              jButtonQuery.setEnabled(true);
            }
        });
    }//GEN-LAST:event_jButtonQueryActionPerformed

    private void jButtonDelimiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelimiterActionPerformed
        set_state(false);

        file_parser.set_delimiter(jTextDelimiter.getText());
    }//GEN-LAST:event_jButtonDelimiterActionPerformed

    private void jMenuHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHelpMouseClicked
         JOptionPane.showMessageDialog(null,"File format : Line will become nodes and columns are the dimensions\nFirst line will be used as names for the dimensions\n1)First set the delimiter you use in your file\n"
                 + "2)Load your data\n3)Execute queries or check data in tree");
    }//GEN-LAST:event_jMenuHelpMouseClicked

    private void jMenuResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuResetMouseClicked
        set_state(true);
        this.jButtonQuery.setEnabled(false);
        jComboBoxHorizontal.setEnabled(false);
        jComboBoxVertical.setEnabled(false);
        jLabelGraphDimensions.setEnabled(false);
        jButtonGenerateGraph.setEnabled(false);
       if(query_window!=null) query_window.destroy();
       if(this.range_tree!=null) this.range_tree=null;
    }//GEN-LAST:event_jMenuResetMouseClicked

    private void set_state(Boolean unset){
        jButtonDelimiter.setEnabled(unset);
        jTextDelimiter.setEnabled(unset);
        jButtonLoadData.setEnabled(!unset);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelimiter;
    private javax.swing.JButton jButtonLoadData;
    private javax.swing.JButton jButtonQuery;
    private javax.swing.JButton jButtonGenerateGraph;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenu jMenuReset;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextPane jTextDelimiter;
    private javax.swing.JComboBox<String> jComboBoxHorizontal;
    private javax.swing.JComboBox<String> jComboBoxVertical;
    private javax.swing.JLabel jLabelGraphDimensions;
    public javax.swing.JLabel jLabelHorizontal;
    public javax.swing.JLabel jLabelVertical;
    private javax.swing.JProgressBar jProgressBarTree;
    private javax.swing.JLabel jLabelPercent;
    public javax.swing.JPanel jPanelTools;

    // End of variables declaration//GEN-END:variables
}
